config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'restaurants#index'

  resources :restaurants do
  	resources :reviews, except: [:index, :show]
    resources :complaints, except: [:index, :edit, :update] do
      collection do
        get 'all'
      end
    end
  	collection do
  		get 'search'
      get 'hidden'
  	end
    member do
      get 'hide'
      get 'display'
    end
  end

  resources :supports, except: [:index, :update] do
    collection do
      get 'all'
    end
  end

  match '/about_us', to: 'pages#about_us', via: :get
  match '/complaints', to: 'complaints#all_complaints', via: :get
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :restaurants
end

app/models/complaint.rb
class Complaint < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews
  has_many :complaints
  belongs_to :category

  validates_presence_of :name
  validates_presence_of :description
  validates_presence_of :address
  validates_presence_of :city
  validates_presence_of :state
  validates_presence_of :zipcode

  geocoded_by :full_address
  after_validation :geocode

  def full_address
    [address, city, state, zipcode].join(', ')
  end

  def self.search(params)
    restaurants = Restaurant.where(hidden: false)
    restaurants = restaurants.where(category_id: params[:category].to_i) #TO-DO: change so category is optional
    restaurants = restaurants.where("name like ? or description like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%") if params[:keyword].present?
    begin
      restaurants = restaurants.near(params[:location], 15) if params[:location].present?
    rescue
      restaurants = []
    end
    #TO-DO: filter restaurants that are open
    restaurants
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user
end

app/models/support.rb
class Support < ActiveRecord::Base

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :complaints
  validates_presence_of :first_name
  validates_presence_of :last_name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password) }
      devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password) }
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

end

app/controllers/complaints_controller.rb
class ComplaintsController < ApplicationController
  before_action :authenticate_user!

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @complaint = Complaint.new(restaurant: @restaurant)
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @complaint = current_user.complaints.build(complaint_params)
    @complaint.restaurant = @restaurant
    @complaint.save
    redirect_to @restaurant
  end

  def all
    @restaurant = Restaurant.find(params[:restaurant_id])
    @complaints = Complaint.where(restaurant: @restaurant)
  end

  def all_complaints
    @complaints = Complaint.all
  end

  private
    def complaint_params
      params.require(:complaint).permit(:body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

	def about_us
		
	end

	def contact_us

	end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new]
  before_action :is_admin?, only: [:edit, :update, :destroy, :hide, :display, :hidden]

  def index
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant
    else
      flash[:danger] = @restaurant.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    @reviews = Review.where(restaurant_id: @restaurant)
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to @restaurant
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to root_path
  end

  def search
    @restaurants = Restaurant.search(params)
  end

  def hidden
    @restaurants = Restaurant.where(hidden: true)
  end

  def hide
    @restaurant = Restaurant.find(params[:id])
    @restaurant.write_attribute(:hidden, true)
    @restaurant.save
    flash[:notice] = @restaurant.name + " is now hidden!"
    redirect_to @restaurant
  end

  def display
    @restaurant = Restaurant.find(params[:id])
    @restaurant.write_attribute(:hidden, false)
    @restaurant.save
    flash[:notice] = @restaurant.name + " is now displayed!"
    redirect_to @restaurant
  end

  private
    def restaurant_params
      params.require(:restaurant).permit(:name, :description, :address, :city, :state, :zipcode, :phone, :category_id)
    end

    def is_admin?
      if !current_user.try(:admin)
        flash[:danger] = "You are not authorized to do this!"
        redirect_to root_path
      end
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :set_restaurant
	before_action :authenticate_user!

	def new
		@review = Review.new(restaurant: @restaurant)
	end

	def create
		@review = current_user.reviews.build(review_params)
		@review.restaurant = @restaurant
		@review.save
		redirect_to @restaurant
	end

	private
		def set_restaurant
			@restaurant = Restaurant.find(params[:restaurant_id])
		end
		def review_params
			params.require(:review).permit(:comment, :rating)
		end
end

app/controllers/supports_controller.rb
class SupportsController < ApplicationController
  before_action :is_admin?, only: [:all]

  def new
    @support = Support.new
  end

  def create
    @support = Support.new(supports_params)
    if @support.save
      redirect_to root_path
    else
      flash[:danger] = @support.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def all
    @supports = Support.all
  end

  def destroy
    @support = Support.find(params[:id])
    @support.destroy
    redirect_to all_supports_path
  end

  private
    def supports_params
      params.require(:support).permit(:name, :body)
    end

    def is_admin?
      if !current_user.try(:admin)
        flash[:danger] = "You are not authorized to do this!"
        redirect_to root_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-danger"> <button type="button"
    class="close" data-dismiss="alert">×</button>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

app/views/complaints/all.html.erb
<div class="bg-content">
  <!--  content  -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <div class="inner-1">
            <h3><%= @restaurant.name %> Complaints</h3>
            <% if @complaints.blank? %>
              <p>None!</p>
            <% else %>
              <% @complaints.reverse_each do |r| %>
                <ul class="list extra extra1">
                  <li>
                    <% begin %><%= "#{r.user.first_name} #{r.user.last_name}" %><% rescue %>Unknown<% end %><i> said:<br>
                    <%= r.body %></i><br>
                  </li>
                </ul>
              <% end %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/complaints/all_complaints.html.erb
<div class="bg-content">
  <!--  content  -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <div class="inner-1">
            <h3>All Complaints</h3>
            <% if @complaints.blank? %>
              <p>None!</p>
            <% else %>
              <% @complaints.reverse_each do |r| %>
                <ul class="list extra extra1">
                  <li>
                    <% begin %><%= "#{r.user.first_name} #{r.user.last_name}" %><% rescue %>Unknown<% end %><i> said about 
                    <% begin %><%= "#{r.restaurant.name}" %><% rescue %>Unknown<% end %>:<br>
                    <%= r.body %></i><br><br>
                  </li>
                </ul>
              <% end %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/complaints/new.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <h3>Add new complaint</h3>
          <div class="inner-1">
            <%= form_for [@restaurant, @complaint], url: {action: "create"} do |f| %>
            	<%= f.label :body %>
      				<%= f.text_area :body %><br>
      				<%= f.submit class:"btn btn-1"%>
    			  <% end %>
          </div>
        </article>
      </div>
   </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!--==============================
              footer
=================================-->
<footer>
  <div class="container clearfix">
    <ul class="list-social pull-right">
      <li><a class="icon-1" href="#"></a></li>
      <li><a class="icon-2" href="#"></a></li>
      <li><a class="icon-3" href="#"></a></li>
      <li><a class="icon-4" href="#"></a></li>
    </ul>
    <div class="privacy pull-left">&copy; 2013 | <a href="http://www.dzyngiri.com">Dzyngiri</a> | Demo Illustrations by <a href="http://justinmezzell.com">Justin Mezzell</a></div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container clearfix">
    <div class="row">
      <div class="span12">
        <div class="navbar navbar_">
          <div class="container">
            <h1 class="brand brand_"><%= link_to(image_tag("logo.png"), root_path) %></h1>
            <a class="btn btn-navbar btn-navbar_" data-toggle="collapse" data-target=".nav-collapse_">Menu <span class="icon-bar"></span> </a>
            <div class="nav-collapse nav-collapse_  collapse">
              <ul class="nav sf-menu">
                <li><%= link_to "About us", about_us_path %></li>
                <li><%= link_to "Contact", new_support_path %></li>
                <% if user_signed_in? %>
                  <li><%= link_to "Account", edit_user_registration_path %></li>
                  <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign in", new_user_session_path %></li>
                  <li><%= link_to "Register", new_user_registration_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_searchform.html.erb
<div class="bg-content">
  <div class="container">
    <div class="row">
      <article class="span12">
        <h4>Search for a restaurant:</h4>
        <!-- start search form -->
        <%= form_tag search_restaurants_path, method: :get do |f| %>
          <%= text_field_tag :keyword, nil, placeholder: "steaks, pasta, etc." %>
          <%= text_field_tag :location, nil, placeholder: "Houston, Santa Clara, etc." %>
          <%= select_tag :category, options_for_select(Category.all.map{|i| [i.name, i.id]}) %><br>
          <%= submit_tag "Search", class:"btn btn-1" %>
        <% end %>
        <!-- end search form -->
      </article>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantAdvisor</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-content">
  	<%= render 'layouts/header' %>
    <div class="bg-content">
      <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>">
          <a href="#" data-dismiss="alert" class="close">×</a>
          <ul>
            <li>
              <%= value %>
            </li>
          </ul>
        </div>
      <% end %>
      </div>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about_us.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <h3>Developers</h3>
            <h5>Quang Duy Luong</h5>
            <p>Email: quangduy.luong@sjsu.edu</p>

            <h5>Jie Peng Hu</h5>
            <p>Email: jiepeng.huwu@sjsu.edu</p>

            <h5>Su Pyae Tun</h5>
            <p>Email: supyae.tun@sjsu.edu</p>

            <h5>Yihua Li</h5>
            <p>Email: yihua.li@sjsu.edu</p>
          
        </article>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/edit.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <h3>Edit restaurant</h3>
          <div class="inner-1">
            <%= form_for (@restaurant), url: {action: "update"} do |f| %>
              <%= f.label :name %>
              <%= f.text_field :name %><br>
              <%= f.label :description %>
              <%= f.text_area :description %><br>
              <%= f.select :category_id, Category.all.map { |f| [f.name, f.id] } %>
              <%= f.label :address %>
              <%= f.text_field :address %><br>
              <%= f.label :city %>
              <%= f.text_field :city %><br>
              <%= f.label :state %>
              <%= f.text_field :state %><br>
              <%= f.label :zipcode %>
              <%= f.text_field :zipcode %><br>
              <%= f.label :phone %>
              <%= f.text_field :phone %><br>
              <%= f.submit class:"btn btn-1" %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/hidden.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
        <% if @restaurants.blank?%>
          <h3>Couldn't find any hidden restaurants.</h3>
        <% else %>
          <% @restaurants.each do |f| %>
            <h3><%= link_to f.name, f %> </h3> 
            <br><br><br>
          <% end %>
        <% end %>
      </article>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/index.html.erb
<div class="bg-content">
<!-- content -->
  <div id="content" class="content-extra">
    <div class="ic"></div>
    <!-- searchform here -->
    <%= render 'layouts/searchform' %>
    <!-- end searchform -->
    <div class="row-2">
      <div class="container">
        <h3>Found new restaurant?</h3>
        <h3>Tell us about it below!</h3>
        <p>We will review it and add it to our list.</p>
        <%= link_to "Add new restaurant", new_restaurant_path, class:"btn btn-1" %> 
        <% if current_user.try(:admin) %>
          <%= link_to "Hidden Restaurants", hidden_restaurants_path, class:"btn btn-1" %>
          <%= link_to "Complaints", complaints_path, class:"btn btn-1" %>
          <%= link_to "Support List", all_supports_path, class:"btn btn-1" %>
        <% end %>
      </div>
    </div>
    <div class="container">
      <div class="row">
        <article class="span6">
          <br><%= image_tag("food01.jpg") %><br><br>
          <%= image_tag("food04.jpg") %><br><br>
          <%= image_tag("food06.jpg") %>
        </article>
        <article class="span6">
          <br><%= image_tag("food05.jpg") %><br><br>
          <%= image_tag("food02.jpg") %><br><br>
          <%= image_tag("food03.jpg") %>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <h3>Add new restaurant</h3>
          <div class="inner-1">
            <%= form_for (@restaurant), url: {action: "create"} do |f| %>
              <%= f.label :name %>
              <%= f.text_field :name %><br>
              <%= f.label :description %>
              <%= f.text_area :description %><br>
              <%= f.select :category_id, Category.all.map { |f| [f.name, f.id] } %>
              <%= f.label :address %>
              <%= f.text_field :address %><br>
              <%= f.label :city %>
              <%= f.text_field :city %><br>
              <%= f.label :state %>
              <%= f.text_field :state %><br>
              <%= f.label :zipcode %>
              <%= f.text_field :zipcode %><br>
              <%= f.label :phone %>
              <%= f.text_field :phone %><br>
              <%= f.submit class:"btn btn-1" %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/search.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <!-- searchform here -->
    <%= render 'layouts/searchform' %>
    <!-- end searchform -->
    <div class="container">
      <div class="row">
        <article class="span8">
        <% if @restaurants.blank?%>
          <h3>Could not find any restaurant matching the specified parameters, Please try again. </h3>
        <% else %>
          <% @restaurants.each do |f| %>
            <h3><%= link_to f.name, f %> </h3> <% if f.reviews.blank? %>(0.0)
              <% else%>(<%= (f.reviews.average(:rating)).round(2) %>)<% end%>
            <br><br><br>
          <% end %>
        <% end %>
      </article>
      </div>
    </div>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="bg-content">
  <!--  content  -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <div class="inner-1">
            <h3><%= @restaurant.name %> <% if @reviews.blank? %>(0.0)
              <% else%>(<%= (@reviews.average(:rating)).round(2) %>)<% end%></h3>
            <i><%= @restaurant.description %></i>
            <hr>
            <ul class="list extra extra1">
              <li>Type of food: <%= @restaurant.category.name %></li>
              <li>Address:<br> 
                <%= @restaurant.address %><br>
                <%= @restaurant.city %>, <%= @restaurant.state %><br>
                <%= @restaurant.zipcode %><br>
              <li>Phone: <%= @restaurant.phone %><br></li>
            </ul>
            <!-- a href="#" class="btn btn-1">Visit Website</a -->
            <hr>
            <h3>Reviews</h3>
            <% if @reviews.blank? %>
              <p>Be the first to leave a review!</p>
            <% else %>
              <% @reviews.reverse_each do |r| %>
                <ul class="list extra extra1">
                  <li>
                    <% begin %><%= "#{r.user.first_name} #{r.user.last_name}" %><% rescue %>Unknown<% end %><i> said:<br>
                    (<%= r.rating %>/5) <%= r.comment %></i><br><br>
                  </li>
                </ul>
              <% end %>
            <% end %>
            <%= link_to "Write a review", new_restaurant_review_path(@restaurant), class:"btn btn-1" %><br><hr>
            <p>Misleading information or really poor service? Let us know below!</p>
            <%= link_to "Complain", new_restaurant_complaint_path(@restaurant), class:"btn btn-1" %><br>
          </div>
        </article>
        <article class="span4">
          <h3></h3>
          <iframe
            width="100%"
            height="300px"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCvDqoYH97URG_TFYHZTg7w4-5Q862-XO8
              &q=<%= @restaurant.full_address %>" allowfullscreen>
          </iframe>
          <% if current_user.try(:admin?) %>
            <h3>Admin options:</h3>
            <%= link_to "Edit Information", edit_restaurant_path %><br>
            <%= link_to "Delete Restaurant", restaurant_path, method: :delete %><br>
            <%= link_to "Show Complaints", all_restaurant_complaints_path(@restaurant) %><br>
            <% if @restaurant.hidden? %>
              <%= link_to "Make Visible", display_restaurant_path(@restaurant) %><br>
            <% else %>
              <%= link_to "Make Hidden", hide_restaurant_path(@restaurant) %><br>
            <% end %>
          <% end %>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/reviews/new.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <h3>Add new review</h3>
          <div class="inner-1">
            <%= form_for [@restaurant, @review], url: {action: "create"} do |f| %>
            	<%= f.label :comment %>
      				<%= f.text_area :comment %><br>
      				<%= f.label :rating %>
      				<%= f.number_field :rating, value: 1, min: 1, max: 5 %><br>
      				<%= f.submit class:"btn btn-1"%>
    			  <% end %>
          </div>
        </article>
      </div>
   </div>
  </div>
</div>

app/views/supports/all.html.erb
<div class="bg-content">
  <!--  content  -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <div class="inner-1">
            <h3>Support list</h3>
            <% if @supports.blank? %>
              <p>None!</p>
            <% else %>
              <% @supports.reverse_each do |r| %>
                <ul class="list extra extra1">
                  <li>
                    <%= "#{r.name}" %><i> said:<br>
                    <%= r.body %></i><br><br>
                  </li>
                </ul>
              <% end %>
            <% end %>
          </div>
        </article>
      </div>
    </div>
  </div>
</div>

app/views/supports/new.html.erb
<div class="bg-content">
  <!-- content -->
  <div id="content">
    <div class="ic"></div>
    <div class="container">
      <div class="row">
        <article class="span8">
          <h3>Contact us</h3>
          <div class="inner-1">
            <%= form_for [@support], url: {action: "create"} do |f| %>
              <%= f.label :name %>
              <%= f.text_field :name %><br>
            	<%= f.label :body %>
      				<%= f.text_area :body %><br>
      				<%= f.submit class:"btn btn-1"%>
    			  <% end %>
          </div>
        </article>
      </div>
   </div>
  </div>
</div>